# syntax=docker/dockerfile:1
FROM python:3.11-alpine

# Environment setup
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
RUN mkdir -p /opt/app /opt/app/config
WORKDIR /opt/app

# Set python path for config directory
RUN touch /opt/app/config/__init__.py
ENV PYTHONPATH "/opt/app"

# System packages
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# Python packages
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy entrypoint
COPY ./config/docker/development/entrypoint.dev.sh .
RUN chmod +x /opt/app/entrypoint.dev.sh

# Copy app
COPY ./app/ /opt/app/src/

# Final environment
WORKDIR /opt/app/src
ENV BASE_DIR /opt/app/src

# Run entrypoint.sh.
ENTRYPOINT ["/opt/app/entrypoint.dev.sh"]
